### ISSUE TITLE
Incorporate client Feedback

### ISSUE THREAD

**Issue by Trullfax** [Buecher-Heimat/writing-competition-web#37]
1. Wettbewerbseite
- [ ] Jury: soll die namentlich genannt werden oder nicht? evtl. Fotos
- [x] "So geht's" | Untertitel = Es ist ganz einfach | Das Unwort "eigentlich" streichen

2. Formular
- ~Statt „müssen Deine Eltern….bestätigen“ besser „müssen Deine Eltern Deine Teilnahme und die Teilnahmebedingungen bitte schriftlich bestätigen“~
- [x] Altersgruppen anklickbar machen ODER Einteilungsfelder streichen
- [x] (Schreibe hier Deinen Text...) soll automatisch verschwinden, damit er nicht ungewollt im Text stehen bleibt
- [x] im Text zur Bestätigungsmail den Hinweis einbauen, man möge auch im Spam nachschauen.

3. Allgemein
- [ ] Abstufung der Gewinner (Was ist ein Gewinner konkret?! ggf. könnten Gewinnkategorien in "Unsere Vorgaben" definiert werden)

WEITERE ANMERKUNG FÜRS PROTOKOLL
- [ ] Mailadresse für Bestätigungsmail funktioniert nicht
- ~Eingereichte Texte im Blocksatz~

**Comment by Trullfax** [comment]
EIGENE ANMERKUNGEN
- In der Anmerkung im Formular "Wir empfehlen Dir, deinen Beitrag an einem PC mit einem großen Bildschirm und einer Tastatur einzureichen!" hinzufügen, dass man es auf dem Gerät machen sollte, wo man auch den Text gespeichert hat
- Schriftart auf der Startseite für "Bad Harzburg" anpassen
- Mitmachen Buttons am Ende von Seiten einheitlich machen

**Comment by Importantus** [comment]
Weiteres Feedback:

- [ ] Statt "Mitmachen" "Text einreichen" in den CTAs
- [ ] Link unter "Text einreichen" verknüpfen oder entfernen
- [ ] Mitmachen-Fomular/Email-Bestätigen Modal: Wettbewerbstitel in Anführungszeichen, bei E-Mail-Adresse fehlt ein Bindestrich, Hinweis auf Spam-Ordner
- [ ] Min-Height 100vh für Hintergrundformen auf der Text-Seite
- [ ] Datenschutzerklärung
